### ISSUE TITLE
Parent task disabled but only first child reflects being disabled

### ISSUE THREAD

**Issue by eddiejaoude** [kestra-io/ui-libs#561]
Original bug on the **Kestra** repo, but the actual code changes are on this repo https://github.com/kestra-io/kestra/issues/6754#issuecomment-2945100049

When the parent task is disabled only the first child is disabled, subsequent tasks are not.

<img width="2845" alt="Image" src="https://github.com/user-attachments/assets/4ea2fa69-b447-4fc4-93fe-971c97f5a7fa" />

```yaml
  - id: parallel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: string
        disabled: true
        type: io.kestra.plugin.core.flow.Sequential
        tasks:
          - id: stringSet
            type: io.kestra.plugin.redis.string.Set
            url: "{{ vars.dockerUrl }}"
            key: "string_{{ execution.id }}"
            value: "{{ flow.id }}"
            serdeType: STRING

          - id: stringGet
            type: io.kestra.plugin.redis.string.Get
            url: "{{ vars.dockerUrl }}"
            key: "string_{{ execution.id }}"
            serdeType: STRING
```

*The original issue https://github.com/kestra-io/kestra/issues/6754#issuecomment-2945100049 is assigned to me, please also assign this issue to me.*
